packages:
  - "."
minimumReleaseAgeExclude:
  - '@opencode/ai@2.0.14'
  - '@opencode/client@2.0.14'
  - '@opencode/codemode@2.0.14'
  - '@opencode/core@2.0.14'
  - '@opencode/plugin@2.0.14'
  - '@opencode/plugin-browser@2.0.14'
  - '@opencode/protocol@2.0.14'
  - '@opencode/schema@2.0.14'
  - '@opencode/sdk@2.0.14'
  - '@opencode/server@2.0.14'
  - '@opencode/simulation@2.0.14'
  - '@opencode/util@2.0.14'
allowBuilds:
  '@parcel/watcher': false
  msgpackr-extract: false
  protobufjs: false
  tree-sitter-bash: false
  tree-sitter-powershell: false
